cloud:
  aws:
    credentials:
      access-key: ${ACCESS-KEY}
      secret-key: ${SECRET-KEY}
    region:
      static: ap-northeast-2
    s3:
      user-bucket : ${USER-BUCKET}
      review-img : ${REVIEW-IMG}
      restaurant-bucket : ${RESTAURANT-BUCKET}
